# Generated by Django 4.2.27 on 2025-12-17 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, help_text='Unique identifier for the customer', max_length=100, unique=True)),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when customer was created')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the campaign')),
                ('discount_type', models.CharField(choices=[('CART', 'Cart Discount'), ('DELIVERY', 'Delivery Discount')], help_text='Type of discount: CART or DELIVERY', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Flat discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_date', models.DateField(help_text='Campaign start date')),
                ('end_date', models.DateField(help_text='Campaign end date')),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total budget allocated for this campaign', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('consumed_budget', models.DecimalField(decimal_places=2, default=0, help_text='Amount of budget already consumed', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_transactions_per_customer_per_day', models.PositiveIntegerField(help_text='Maximum number of times a customer can use this campaign per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the campaign is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when campaign was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when campaign was last updated')),
                ('targeted_customers', models.ManyToManyField(help_text='Customers who are eligible for this campaign', related_name='campaigns', to='campaigns.customer')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(help_text='The date of usage')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times used on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('campaign', models.ForeignKey(help_text='The campaign being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='campaigns.campaign')),
                ('customer', models.ForeignKey(help_text='The customer using the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usages', to='campaigns.customer')),
            ],
            options={
                'verbose_name': 'Campaign Usage',
                'verbose_name_plural': 'Campaign Usages',
                'ordering': ['-usage_date', '-updated_at'],
                'indexes': [models.Index(fields=['campaign', 'customer', 'usage_date'], name='campaigns_c_campaig_c8ce71_idx'), models.Index(fields=['usage_date'], name='campaigns_c_usage_d_f29782_idx')],
                'unique_together': {('campaign', 'customer', 'usage_date')},
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['discount_type'], name='campaigns_c_discoun_942fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_c_start_d_996cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_c_is_acti_7a198a_idx'),
        ),
    ]
